/**
 * Script de migración: importa Clientes y Servicios desde Excel a Supabase.
 * Ejecutar: node scripts/importar-excel.mjs
 *
 * PRE-REQUISITO (Supabase SQL Editor):
 *   ALTER TABLE servicios ALTER COLUMN id SET GENERATED BY DEFAULT;
 *
 * POST-EJECUCIÓN (Supabase SQL Editor):
 *   SELECT setval(pg_get_serial_sequence('servicios', 'id'), (SELECT MAX(id) FROM servicios));
 */

import { readFileSync } from 'fs'
import { fileURLToPath } from 'url'
import { dirname, join } from 'path'
import { createClient } from '@supabase/supabase-js'
import ws from 'ws'
import XLSX from 'xlsx'
import dotenv from 'dotenv'

const __dirname = dirname(fileURLToPath(import.meta.url))
dotenv.config({ path: join(__dirname, '..', '.env.local') })

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL
const SUPABASE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY

if (!SUPABASE_URL || !SUPABASE_KEY) {
  console.error('ERROR: Faltan variables NEXT_PUBLIC_SUPABASE_URL o SUPABASE_SERVICE_ROLE_KEY en .env.local')
  process.exit(1)
}

const supabase = createClient(SUPABASE_URL, SUPABASE_KEY, {
  realtime: { transport: ws },
})

const EXCEL_PATH = join(__dirname, '..', 'recursos', 'migracion', 'importacion.xlsx')
const BATCH_SIZE = 100

const ESTADO_MAP = {
  'TERMINADO':    'TERMINADO',
  'EN PROCESO':   'EN PROCESO',
  'CANCELADO':    'CANCELADO',
  'RECHAZADO':    'RECHAZADO',
  'INGRESADO':    'INGRESADO',
  'PRESUPUESTADO':'PRESUPUESTADO',
}
const ESTADO_PAGO_MAP = {
  'PAGADO':       'PAGADO',
  'NO PAGADO':    'PENDIENTE',
  'SIN CARGO':    'SIN CARGO',
  'PAGO PARCIAL': 'PAGO PARCIAL',
  'GARANTIA':     'GARANTIA',
}

function toFecha(val) {
  if (!val) return null
  if (val instanceof Date) return val.toISOString().split('T')[0]
  if (typeof val === 'string' && /^\d{4}-\d{2}-\d{2}/.test(val)) return val.slice(0, 10)
  return null
}

function toTelefono(val) {
  if (!val) return null
  return String(val).trim() || null
}

async function importarClientes(rows) {
  console.log(`\n=== FASE 1: Importando ${rows.length} clientes ===`)
  const clienteMap = new Map() // Cod_Cliente_viejo → nuevo ID Supabase
  let importados = 0
  let errores = 0

  for (let i = 0; i < rows.length; i += BATCH_SIZE) {
    const batch = rows.slice(i, i + BATCH_SIZE)
    const insertData = batch.map((row) => ({
      nombre:              row.Razon_Social ? String(row.Razon_Social).trim() : '(sin nombre)',
      tipo:                'PARTICULAR',
      direccion:           row.Direccion    ? String(row.Direccion).trim()    : null,
      localidad:           row.Localidad    ? String(row.Localidad).trim()    : null,
      telefono:            toTelefono(row.Telefono),
      email:               row.Email        ? String(row.Email).trim()        : null,
      notas:               row.Contacto     ? String(row.Contacto).trim()     : null,
      activo:              true,
      mostrar_en_landing:  false,
    }))

    const { data, error } = await supabase
      .from('clientes')
      .insert(insertData)
      .select('id')

    if (error) {
      console.error(`  Batch ${i / BATCH_SIZE + 1} ERROR:`, error.message)
      errores += batch.length
    } else {
      data.forEach((d, idx) => clienteMap.set(batch[idx].Cod_Cliente, d.id))
      importados += data.length
    }

    if ((i / BATCH_SIZE + 1) % 10 === 0 || i + BATCH_SIZE >= rows.length) {
      console.log(`  Progreso: ${Math.min(i + BATCH_SIZE, rows.length)}/${rows.length} clientes...`)
    }
  }

  console.log(`  ✓ Importados: ${importados} | Errores: ${errores}`)
  return clienteMap
}

async function importarServicios(rows, clienteMap) {
  console.log(`\n=== FASE 2: Importando ${rows.length} servicios ===`)
  let importados = 0
  let errores = 0
  let sinCliente = 0

  for (const row of rows) {
    const nroServicio = row['Nro Servicio']
    const codCliente  = row['CodCliente']
    const clienteId   = clienteMap.get(codCliente)

    if (!clienteId) {
      console.warn(`  AVISO: Servicio ${nroServicio} — CodCliente ${codCliente} no encontrado, se omite.`)
      sinCliente++
      continue
    }

    const { error } = await supabase.from('servicios').insert({
      id:          nroServicio,
      cliente_id:  clienteId,
      titulo:      row.Problema      ? String(row.Problema).trim()      : '(sin título)',
      descripcion: row.DetalleTrabajo? String(row.DetalleTrabajo).trim(): null,
      estado:      ESTADO_MAP[row.Estado]         ?? 'INGRESADO',
      estado_pago: ESTADO_PAGO_MAP[row.EstadoPago] ?? 'PENDIENTE',
      valor:       row.Valor != null ? Number(row.Valor) : 0,
      fecha:       toFecha(row.FechaIngreso),
    })

    if (error) {
      console.error(`  Servicio ${nroServicio} ERROR:`, error.message)
      errores++
    } else {
      importados++
    }
  }

  console.log(`  ✓ Importados: ${importados} | Sin cliente: ${sinCliente} | Errores: ${errores}`)
}

async function main() {
  console.log('Leyendo Excel:', EXCEL_PATH)
  const wb = XLSX.readFile(EXCEL_PATH, { cellDates: true })

  const clientesRaw = XLSX.utils.sheet_to_json(wb.Sheets['clientes'], { defval: null })
  const serviciosRaw = XLSX.utils.sheet_to_json(wb.Sheets['servicios'], { defval: null })

  // Filtrar filas vacías
  const clientes  = clientesRaw.filter((r) => r.Cod_Cliente != null && r.Razon_Social)
  const servicios = serviciosRaw.filter((r) => r['Nro Servicio'] != null)

  console.log(`Clientes a importar: ${clientes.length}`)
  console.log(`Servicios a importar: ${servicios.length}`)

  const clienteMap = await importarClientes(clientes)

  await importarServicios(servicios, clienteMap)

  console.log('\n=== MIGRACIÓN COMPLETADA ===')
  console.log('Ahora ejecutá en Supabase SQL Editor:')
  console.log("  SELECT setval(pg_get_serial_sequence('servicios', 'id'), (SELECT MAX(id) FROM servicios));")
}

main().catch((err) => {
  console.error('Error fatal:', err)
  process.exit(1)
})
